source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-partial'
gem 'thin'
gem 'jammit'
gem 'github_api'

gem 'sass'
gem 'compass'

gem 'bourbon-compass'
gem 'breakpoint'
gem 'sassy-buttons'
gem 'singularitygs'
gem 'stipe'
gem 'susy'
gem 'neat-compass'
gem 'harsh'
gem 'toolkit'
gem 'color-schemer'
gem 'css-slideshow'
gem 'fancy-buttons'
gem 'modular-scale'
gem 'responsive-sass'
gem 'sassy-math'
gem 'salsa'
gem 'fittext'