source 'http://rubygems.org'
ruby '1.9.3'

gem 'sinatra'
gem 'sinatra-partial'
gem 'unicorn'
gem 'jammit'
gem 'closure-compiler'
gem 'github_api'
gem 'tilt', '1.3.4' # Remove this when 1.3.5+ is good on Heroku.
gem 'thor'
gem 'newrelic_rpm'

gem 'sass'
gem 'compass'

# gem 'haml'
# gem 'slim'

gem 'bourbon-compass'
gem 'breakpoint'
gem 'sassy-buttons'
gem 'singularitygs'
gem 'stipe'
gem 'susy', "~> 2.0.0.alpha"
gem 'neat-compass'
gem 'harsh'
gem 'toolkit'
gem 'color-schemer'
gem 'css-slideshow'
gem 'fancy-buttons'
gem 'modular-scale'
gem 'responsive-sass'
gem 'sassy-math'
gem 'salsa'
gem 'fittext'
gem 'rwdcalc'
gem 'zen-grids'
gem 'blend-mode'
gem 'breakpoint-slicer'
gem 'sassy-text-shadow'
gem 'compass-blend-modes'
gem 'jacket'
gem 'singularity-extras'
