source 'http://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'sass'
gem 'compass'
gem 'sinatra-partial'
gem 'stipe'
gem 'bourbon-compass'
gem 'rake'
gem 'jammit'
gem 'susy'
gem 'sassy-buttons'
gem 'breakpoint'
gem 'singularitygs'